language: ruby
rvm:
- 2.3.3
cache: bundler
before_install:
- chmod +x build.sh
install:
- bundle install
script:
- "./build.sh"
branches:
  only:
  - dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: rTezAErO9ZpVlDOs7M1QqhHtKfEmptpT8bNGzA10KqJGfbgh2+UvywfDqCA40zVp7efjpXQws8eXv2ccm8oT7hFmR5M2KGnE5bYyjAt5ZO0trv1MxA/x+RpGZh3VnK9r8P4QJbPn5TcAcZmfrT5RU2htV3DeV6v9AwgFJ2eKMxS/Zm1wyoqagzUe3y1YKuaGqkEQ31yw/08miFth2nTLLHnd8GwyMqfQPB2Ba+0kwjwrKxcZqEssSu9+IooeDWOkgiqilRJ5OWNY9hJwQSJh3Gvq40kUnI4Jl3KRM+2T3Z+lK0DmXIUIJ5r7L8ktoJm8Fj/g0ST6NWueftx60Yw2yKKlXTFiHXjEq3JG9w1UpkUBlNTFrWO7gp2aKNfULu1g1RSaVEYcL2kOSRm9Qo+sab1wWrOHvK0lRVWxR1ej3afiE5PW+mx2Sh30TgEtRBUKJZolRUuogG0Dg6CWsKbO/sH7+fwkczEMaup1q1TdxBAwGBZ1h3o8MFGiFY9YxpgodwMICuLCj4p0KZOKAsb3cBAmX465wYexkZeHeX6RrqPhBOFdYz1bR1drB3LSpmshRYgkebT0Cwoq90WhtCnhUhKI9oyyUzAutVpPipgF6YaLHTaHQDE3dpHnEIa6BA33r5kmum7DyPJ994c2/PtO081yGVl9BtRWTu1ahUbQDUI=
sudo: false
