language: ruby
rvm:
- 2.3.3

cache: bundler
install:
- bundle install
script:
- "./build.sh"

# after_script:
#  - jekyll es

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - dev     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build


