# File: _config.yml
destination: _site
encoding: UTF-8

title:            Akshata Mohanty - Fullstack Developer @ Rakuten Viki
baseurl:          # /blog

sass:
  sass_dir: styles/_scss

author:
  name:           'Akshata Mohanty'
  url:            https://akshata.dev/


version:            3.0.0
github:
  repo:             https://github.com/akshatamohanty/akshatamohanty.github.io

