# File: _config.yml
destination: _site
encoding: UTF-8
name: Akshata Mohanty | Engineer
description: Learn, Reflect and Engineer. Capturing my journey in print through this website.
url: https://iamaatoh.com
title: Akshata Mohanty | Engineer
permalink: none
sass:
  sass_dir: styles/_scss
author:
  name: "Akshata Mohanty"
  url: https://iamaatoh.com
version: 5.0.0
github:
  repo: https://github.com/akshatamohanty/akshatamohanty.github.io
plugins:
  - jekyll-sitemap
