# File: _config.yml
destination: docs
url: https://iamaatoh.com
baseurl: ""
encoding: UTF-8
name: "Akshata Mohanty (iamaatoh)"
description: "I help companies build genAI data applications to Google Cloud."
permalink: none
author:
  name: "Akshata Mohanty"
  url: https://iamaatoh.com
version: 8.0.0
github:
  repo: https://github.com/akshatamohanty/akshatamohanty.github.io
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
