# File: _config.yml
destination: _dist
encoding: UTF-8
name: aatoh
description: "Coding for fun and food, in that order."
url: https://iamaatoh.com
permalink: none
author:
  name: "aatoh"
  url: https://iamaatoh.com
version: 7.0.0
github:
  repo: https://github.com/akshatamohanty/akshatamohanty.github.io
pagination:
  enabled: true
  per_page: 10
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
