# File: _config.yml
destination: docs
url: "https://iamaatoh.com"
baseurl: ""
encoding: UTF-8
name: "Akshata Mohanty (also known as iamaatoh)"
description: "I help companies deploy cloud-native data applications to production."
permalink: none
author:
  name: "Akshata Mohanty"
  url: https://iamaatoh.com
version: 7.0.0
github:
  repo: https://github.com/akshatamohanty/akshatamohanty.github.io
pagination:
  enabled: true
  per_page: 10
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
