# File: _config.yml
destination: _site
encoding: UTF-8

title:            Brainpickings
baseurl:          # /blog

sass:
  sass_dir: styles/_scss

author:
  name:           'Akshata Mohanty'
  url:            https://akshatamohanty.github.io/


version:            1.0.0
github:
  repo:             https://github.com/akshatamohanty/akshatamohanty.github.io

