# File: _config.yml
destination: _site
encoding: UTF-8
name: Akshata Mohanty | Software Engineer
summary: This is my personal blog, where I write about technology, books and other odd things.
url: https://akshata.dev
title: Akshata Mohanty | Software Engineer
permalink: none
sass:
  sass_dir: styles/_scss
author:
  name:  'Akshata Mohanty'
  url:  https://akshata.dev/
version: 4.0.0
github:
  repo:  https://github.com/akshatamohanty/akshatamohanty.github.io
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "listing"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog"
      category: "blog"
  -
    scope:
      path: "project"
      type: "posts"
    values:
      layout: "project"
      category: "project"
  -
    scope:
      path: "public"
      type: "posts"
    values:
      layout: "public"
      category: "public"