# File: _config.yml
destination: _site
        
# Setup
title:            Brain-pickings
baseurl:          # /blog

sass:
  sass_dir: styles/_scss

author:
  name:           'Akshata Mohanty'
  url:            https://akshatamohanty.github.io/


plugins_dir:
#   - jekyll-feed
#   - jekyll-gist

# Custom vars
version:            1.0.0
github:
  repo:             https://github.com/akshatamohanty/akshatamohanty.github.io

