# File: _config.yml
destination: docs
encoding: UTF-8
name: Akshata / Aatoh
description: "I engineer technology products for fun, efficiency and profit. Futurizing the world one solution at a time. Sharing my insights as I go along."
url: https://iamaatoh.com
title: Akshata Mohanty | Engineer
permalink: none
sass:
  sass_dir: styles/_scss
author:
  name: "Akshata Mohanty"
  url: https://iamaatoh.com
version: 6.0.0
github:
  repo: https://github.com/akshatamohanty/akshatamohanty.github.io
plugins:
  - jekyll-sitemap
