# File: _config.yml
destination: dist

collections:
- projects
- blogs 
- codes

## define a custom collection
# collections:
#   my_collection:
#     output: true

# Setup
title:            Brain Dump
tagline:          'Because all it takes in an idea'
description:      'A foodie-codie blog'
url:              https://akshatamohanty.github.io/
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

sass:
  sass_dir: styles/_scss

author:
  name:           'Akshata Mohanty'
  url:            https://akshatamohanty.github.io/


plugins:
  - jekyll-paginate
#   - jekyll-feed
#   - jekyll-gist

paginate:         10
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Custom vars
version:            1.0.0
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/akshatamohanty/akshatamohanty.github.io

